# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-10 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0022_auto_20160710_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_verify', models.DateTimeField(verbose_name='Дата проверки')),
                ('status_verify', models.CharField(max_length=100, verbose_name='Результат')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Server', verbose_name='Имя сервера')),
                ('type_verify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Verify_type', verbose_name='Название теста')),
            ],
            options={
                'verbose_name': 'Статистику',
                'verbose_name_plural': 'Статистика',
                'ordering': ['name'],
                'db_table': 'Statistics',
            },
        ),
    ]
