#!/usr/bin/python
# -*- coding: utf-8 -*-
import subprocess
import re,sys,os
from datetime import datetime
blue,white,red,invertred,green,orange,invertgreen = [
'\033[36m','\033[0m','\033[31m','\033[31;7m','\033[1;32m','\033[1;31m','\033[32;7m']
try:
	sys.argv[1]
except:
	print "I do nothing excellently!!!"
	os._exit(0)
ip = '10.55.'+sys.argv[1]

def snmpask(ip, oid):
	try:
		p,status = subprocess.Popen('snmpget -v 2c -c ipswitch %s %s' %(ip,oid),shell=True,stdout=subprocess.PIPE).communicate()
		a = p.strip().split(': ')
		if len(a)== 2: return a[1].strip()
		elif len(a) >2:
			a = re.findall('".*"$',p)
			return a[0].strip('"')
		else: return False
	except:
		print "\n %s No response by SNMP %s" %(red,white)

# Если передан ип и он пингается 

if not re.search('^\d+.\d+$',sys.argv[1]): print "Wrong IP %s" %ip; os._exit(0);
if subprocess.call(['ping', '-c', '1', '-W', '1', ip], stdout=open('/dev/null','w'), stderr=open('/dev/null','w')) != 0:
	print "%s No ping by %s %s" %(red,ip,white); os._exit(0);
if not re.search('IP.Net Remote Power Control',snmpask(ip, '.1.3.6.1.2.1.1.1.0')):
	print "%s %s is not DEGL %s" %(red,ip,white); os._exit(0);

for i in range(1,5):
	buf = snmpask(ip, '.1.3.6.1.4.1.26104.1.1.1.2.'+str(i))
	buf1 = snmpask(ip, '.1.3.6.1.4.1.26104.1.1.1.2.'+str(i + 8))
	if buf1:
		dt_obj = datetime.strptime(buf1.strip('"'), "%Y/%m/%d %H:%M:%S")
		now_time = datetime.now().replace(microsecond=0)
		delta = now_time - dt_obj
	else: delta = ''
	if buf == '0': 
		print "%s Zone(%s) : %sNormal %s" %(blue,i,green,white), '\t', delta
	elif buf == '1':
		print "%s Zone(%s) : %sABNORMAL! %s" %(blue,i,invertred,white), '\t', delta
	else: print "%s Zone(%s) : %s %s %s" %(blue,i,orange,buf,white)

buf = snmpask(ip, '.1.3.6.1.4.1.26104.1.1.1.3.4')
if buf == '0': 
	print "%s AC Power: %sNormal%s" %(blue,green,white)
elif buf == '1':
	print "%s AC Power:  %sABNORMAL!%s" %(blue,invertred,white)
else: print "%s AC Power: %s %s %s" %(blue,orange,buf,white)

# buf = snmpask(ip, '.1.3.6.1.4.1.26104.1.1.1.6.1')
# print buf

if not snmpask(ip, '.1.3.6.1.4.1.26104.1.1.1.6.1'):
	print orange + "Outlet (1) not under the ping!" + white
if not snmpask(ip, '.1.3.6.1.4.1.26104.1.1.1.6.2'):
	print orange + "Outlet (2) not under the ping!" + white
