# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя сервера')),
                ('ip', models.GenericIPAddressField(verbose_name='IP сервера')),
                ('date_add', models.DateField(verbose_name='Дата добавления')),
                ('date_edit', models.DateField(verbose_name='Дата редактирования')),
                ('on_off', models.BooleanField(verbose_name='Включение')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Сервера',
                'db_table': 'servers',
                'verbose_name': 'Сервер',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Verify_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('visibility', models.BooleanField(db_index=True, default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': 'Проверки',
                'db_table': 'verify_type',
                'verbose_name': 'Проверка',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='server',
            name='verify',
            field=models.ManyToManyField(to='main.Verify_type', verbose_name='servers'),
        ),
    ]
