# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verify_type',
            options={'ordering': ['name'], 'verbose_name': 'Тип проверки', 'verbose_name_plural': 'Типы проверок'},
        ),
    ]
