# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160331_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='verify',
            field=models.ManyToManyField(related_name='verify_type', to='main.Verify_type'),
        ),
    ]
