# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160331_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='verify',
            field=models.ManyToManyField(to='main.Verify_type'),
        ),
    ]
