# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160331_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify_type',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
