# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160412_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify_type',
            name='comment',
            field=models.TextField(default=True, verbose_name='Комментарий'),
        ),
    ]
