# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_verify_type_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify_type',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
