# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20160412_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ['name'], 'verbose_name': 'Статистику', 'verbose_name_plural': 'Статистика'},
        ),
    ]
