# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20160412_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='verify',
        ),
        migrations.AddField(
            model_name='server',
            name='verify',
            field=models.ManyToManyField(blank=True, related_name='servers', to='main.Verify_type', verbose_name='Проверки'),
        ),
    ]
