# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20160412_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='verify',
        ),
        migrations.AddField(
            model_name='server',
            name='verify',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='main.Verify_type', verbose_name='Проверки'),
        ),
    ]
