# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20160412_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify_type',
            name='name',
            field=models.CharField(help_text='Имя теста', max_length=100, verbose_name='Название'),
        ),
    ]
