# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-10 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20160414_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='name',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='type_verify',
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
