# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-10 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20160710_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.TextField(max_length=30, verbose_name='Имя сервера'),
        ),
        migrations.AlterField(
            model_name='verify_type',
            name='name',
            field=models.CharField(help_text='Название теста', max_length=50, verbose_name='Название'),
        ),
    ]
